apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smart-alarm-web-app-fe.fullname" . }}-nginx-conf
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;

      index index.html;

      location / {
        try_files $uri /index.html;
      }
    }
