apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smart-alarm-web-app-fe.fullname" . }}
  labels:
    app: {{ include "smart-alarm-web-app-fe.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "smart-alarm-web-app-fe.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "smart-alarm-web-app-fe.name" . }}
    spec:
      containers:
        - name: smart-alarm-web-app-fe
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "smart-alarm-web-app-fe.fullname" . }}-nginx-conf
