apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-alarm-web-app-fe.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "smart-alarm-web-app-fe.name" . }}
