---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: traefik
spec:
  controllerName: traefik.io/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
  namespace: smart-alarm
spec:
  gatewayClassName: traefik
  listeners:
  - name: web
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: smart-alarm-route
  namespace: smart-alarm
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: smart-alarm
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /RigAlarmsDashboard
    backendRefs:
    - name: smart-alarm-webapp
      port: 80
