apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: httpbin-ping
  namespace: smart-alarm
spec:
  entryPoints:
    - web
  routes:
  - match: Path(`/api/ping`)
    kind: Rule
    middlewares:
      - name: strip-api
    services:
      - name: smart-alarms-webapp-service
        namespace: smart-alarm
        port: 80