apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  ports:
    - port: 1433
      targetPort: tcpsql
      name: tcpsql
  clusterIP: None   # Headless service required for StatefulSet DNS
  selector:
    app: mssql
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-clusterip
  labels:
    app: mssql
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: tcpsql
      name: tcpsql
  selector:
    app: mssql