apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  rev: 1
spec:
  serviceName: "mssql"
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-express
        ports:
        - containerPort: 1433
          name: tcpsql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: mssql
          mountPath: "/var/opt/mssql"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "4"
        readinessProbe:
          exec:
            command:
            - /opt/mssql-tools/bin/sqlcmd
            - "-S"
            - "localhost"
            - "-U"
            - "sa"
            - "-P"
            - "$(MSSQL_SA_PASSWORD)"
            - "-Q"
            - "SELECT 1"
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /opt/mssql-tools/bin/sqlcmd
            - "-S"
            - "localhost"
            - "-U"
            - "sa"
            - "-P"
            - "$(MSSQL_SA_PASSWORD)"
            - "-Q"
            - "SELECT 1"
          initialDelaySeconds: 30
          periodSeconds: 15
  volumeClaimTemplates:
    - metadata:
        name: mssql
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
          limits:
            storage: 10Gi
