replicaCount: 1

image:
  repository: my-dockerhub-user/react-spa
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []   # add certs here if needed

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
