apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  serviceName: "mssql"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 0
      initContainers:
      - name: fix-permissions
        image: busybox
        securityContext:
          runAsUser: 0
        command: ["sh", "-c", "chown -R 10001:10001 /var/opt/mssql"]
        volumeMounts:
        - name: mssql
          mountPath: /var/opt/mssql
      containers:
      - name: mssql
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 1433
          name: tcpsql
        env:
        - name: ACCEPT_EULA
          value: "{{ .Values.mssql.acceptEula }}"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: MSSQL_SA_PASSWORD
        - name: MSSQL_PID
          value: "{{ .Values.mssql.pid }}"
        volumeMounts:
        - name: mssql
          mountPath: "/var/opt/mssql"
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - >
                /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1
          initialDelaySeconds: 30   # give SQL Server time to start
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - >
                /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1
          initialDelaySeconds: 60   # wait longer before checking liveness
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: mssql
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.storage }}
          limits:
            storage: {{ .Values.persistence.storage }}
